### PR TITLE
Add DiD section

### LINKED ISSUE #10: package & section suggestions
Hi all - first of all, thanks for adding `fwildclusterboot` to the task view! :) 

I have several suggestions for sections / packages to add to the task view. Note that I have not used most of these packages myself - think of these suggestions as 'methods that I would like to see covered in the task view' & 'packages which I would use in my own research'. I'm also happy to open a proper pull request, but thought starting a discussion here might be more convenient.  

## Differences-in-Differences / Event Studies

I think that all the new packages on DiD & Event studies should be mentioned in the Task View, and in fact deserve a dedicated section. I would suggest to consider the following packages: 
- [fixest](https://cran.r-project.org/web/packages/fixest/index.html) 
- [did](https://cran.r-project.org/web/packages/did/index.html)
- [did2s](https://cran.r-project.org/web/packages/did2s/index.html)
It might also be relevant to list packages that help with testing pre-trends, visualizations etc.

## Synthetic Controls 

In a similar spirit, no packages that implement synthetic control methods are mentioned. Candidates here might be
- [Synth](https://cran.r-project.org/web/packages/Synth/index.html)
- [tidysynth](https://cran.r-project.org/web/packages/tidysynth/index.html)
- [synthdid](https://github.com/synth-inference/synthdid) in case it makes its way to CRAN?

## 'Applied Micro Appendix' 

Maybe it would make sense to add a section that highlights several methods that are currently very popular in appendices of 'applied micro' papers? I am thinking of 

- randomization inference (via [ri2](https://cran.r-project.org/web/packages/ri2/vignettes/ri2_vignette.html), maybe [ritest](https://github.com/grantmcdermott/ritest) once it makes its way to CRAN? )
- the wild cluster bootstrap (via [fwildclusterboot](https://cran.r-project.org/web/packages/fwildclusterboot/fwildclusterboot.pdf), [clusterSEs](https://cran.r-project.org/web/packages/clusterSEs/index.html), [sandwich]())
- other methods to deal with a small number of clusters, e.g. via Satterthwaite corrections [clubSandwich](https://cran.r-project.org/web/packages/clubSandwich/index.html), [dfadjust](https://cran.r-project.org/web/packages/dfadjust/index.html)
- sensitivity analysis (via [sensemakr](https://cran.csail.mit.edu/web/packages/sensemakr/index.html), is there a package that implements Oster bounds?)
- mediation analysis (is there a package that implements [Gelbach's regression decomposition](https://www.journals.uchicago.edu/doi/10.1086/683668)) ? 
- multiple hypothesis corrections ([multcomp](https://cran.r-project.org/web/packages/multcomp/index.html); packages that support Westfall-Young and Romano-Wolf adjustments? I have an [experimental package](https://github.com/s3alfisc/wildrwolf) that implements the Romano-Wolf procedure based on the wild bootstrap, but it is still far away from task view quality)
- variance decomposition methods (e.g. [oaxaca](https://cran.r-project.org/web/packages/oaxaca/index.html) for Kitagawa–Oaxaca–Blinder decompositions?)

## Machine Learning & Econometrics 

I would also love to see a section that collects packages that bridge ML and Econometrics, e.g. 
- [hdm](https://cran.r-project.org/web/packages/hdm/index.html)
- [DoubleML](https://cran.r-project.org/web/packages/DoubleML/index.html)
- [grf](https://cran.r-project.org/web/packages/grf/index.html)

## Other minor suggestions

I would mention `fixest::wald()` in "Further inference and nested model comparisons". 

Best, Alex

### PR DESCRIPTION
**Pull request by grantmcdermott**
Closes #10 (updates to some IV packages notwithstanding)

Note that I wrapped DiD together with IV and RDD under a "canonical research designs" heading. This seemed to me the most logical way to include these three sections. But we can easily change back if you don't like.

### CODE REVIEW

**Comment by zeileis** [comment]
Grant @grantmcdermott thanks for this! Feel free to merge this into the main branch.

The only question/comment I have: Is "canonical research designs" a commonly-used umbrella term for this? Maybe "research designs for causal inference" would be a bit more explicit? But I'm not sure what most readers would find intuitive here.

**Comment by grantmcdermott** [comment]
Great. 

RE: Canonical Research Designs. I think I stole the phrasing from @paulgp, who in turn inherited it from Gary Chamberlain (I believe, although I might be making this up entirely). Happy to switch it out to something like your suggestion if that's more palatable.

Let me think it over tonight. I might add a quick synthetic control bullet point under the DiD heading too. It's a bit awkward having SC and DiD in the same section. But there is an overlap i.t.o. packages and it's not a bad compromise given that SC is mostly a topic for the Casual Inference TaskView.

**Comment by paulgp** [comment]
I think I just made it up (although wouldn't put it past me to have subconsciously gotten it from Gary Chamberlain) for my class lectures: https://github.com/paulgp/applied-methods-phd

It's a useful distinction from just pure "strict ignorability" type causal inference, such as RCTs, given that there seems to be a set number of research approaches that everyone needs in their toolhouse (DiD, RD, and IV).

**Comment by grantmcdermott** [comment]
> It's a useful distinction from just pure "strict ignorability" type causal inference, such as RCTs, given that there seems to be a set number of research approaches that everyone needs in their toolhouse (DiD, RD, and IV).

Yeah, I like it a lot for that reason. I'll fully credit you (and you only!) from now on ;-)

**Comment by paulgp** [comment]
Hah! I don't need the credit, but glad it's catchy and useful. :-)

**Comment by zeileis** [comment]
Nice! Grant @grantmcdermott feel free to add a short reference/link in the introductory paragraph to that section in the task view.

**Pull request merged**
